name: Deploy

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:       
    - name: Deploy using SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          # Change directory to the initial project location
          cd /var/www/postgres-demo2/

          # Pull the latest changes from the repository
          git pull origin main

          # Change directory to the Docker setup location
          cd /opt/docker-setups/maven

          # Build and start Docker containers in detached mode
          docker-compose up --build -d

          # Optionally, log the actions performed
          echo "Docker containers have been built and started in detached mode" >> /var/log/github-actions
